//
// Copyright (c) 2002-2018 WEINZIERL ENGINEERING GmbH
// All rights reserved.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,
// WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
//

#ifndef __KDRIVE_KNX_HEADERS_H__
#define __KDRIVE_KNX_HEADERS_H__

#include "kdrive/knx/Config.h"
#include "kdrive/knx/core/Headers.h"
#include "kdrive/knx/datapoint/Headers.h"
#include "kdrive/knx/defines/Headers.h"
#include "kdrive/knx/telegrams/Headers.h"

#endif // __KDRIVE_KNX_HEADERS_H__
