//
// Copyright (c) 2002-2019 WEINZIERL ENGINEERING GmbH
// All rights reserved.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,
// WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
//

#ifndef __KDRIVE_IO_USBHID_FORWARDS_H__
#define __KDRIVE_IO_USBHID_FORWARDS_H__

#include "kdrive/io/usbhid/Config.h"

namespace kdrive
{
namespace io
{
namespace usb
{

class UsbDriver;
class UsbDriverEnumerator;
class UsbVendors;

}
}
} // end namespace kdrive::io::usb

#endif // __KDRIVE_IO_USBHID_FORWARDS_H__
