//
// Copyright (c) 2002-2019 WEINZIERL ENGINEERING GmbH
// All rights reserved.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY,
// WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE
//

#ifndef __KDRIVE_BAOS_STREAM_HEADERS_H__
#define __KDRIVE_BAOS_STREAM_HEADERS_H__

#include "kdrive/baos/stream/StreamConnection.h"
#include "kdrive/baos/stream/StreamConnector.h"
#include "kdrive/baos/stream/StreamConnector12.h"
#include "kdrive/baos/stream/StreamConnector2x.h"

#endif // __KDRIVE_BAOS_STREAM_HEADERS_H__
