= Migration Guide BAOS SDK from 14.1.1p1 to 15.1.0

== General

=== Compiler

We migrade from {cpp}0x to {cpp}11. So your compiler must support {cpp}11.
The minimum supported compilers version are Visual Studio 2013 and GCC 4.8.


== {cpp} Implementation

=== Library Name

- Renamed from *kdriveRPC_baos* to *kdriveBAOS*
- In kdriveBAOS are now all kdrive components. Before the components are split in own library e.g. wzfUtility, kdriveKnx, ...


=== Include Path

The path was moved from kdrive/baos/rpc/* to kdrive/baos/*

[source, c++]
.old
----
#include <kdrive/baos/rpc/Baos.h>
----

[source, c++]
.new
----
#include <kdrive/baos/Baos.h>
----


=== Namespace

The namespace was renamed from kdrive::rpc::baos to kdrive::baos

[source, c++]
.old
----
using namespace kdrive::rpc::baos;
using kdrive::rpc::baos::BaosConnector;
----

[source, c++]
.new
----
using namespace kdrive::baos;
using kdrive::baos::BaosConnector;
----


=== StreamConnection and ScopedStreamConnection

In this version we implemented support for the BAOS Protocol via FT 1.2.
We renamed the StreamConnection to BaosConnection and extended it for the serial devices.
The connect functions are renamed.
The API from StreamConnection and ScopedStreamConnection is unchanged.
They are used BaosConnection/ScopedBaosConnection and exists only for backward compatibility.

[source, c++]
.old
----
// create a TPC/IP connection with the remote BAOS device

// with ScopedStreamConnection
ScopedStreamConnection connection("Baos-Sample");
BaosConnector::Ptr connector = connection.getConnector();

// or with StreamConnection
StreamConnection connection;
connection.connect("192.168.1.63", 0x20);
BaosConnector::Ptr connector = connection.getConnector();
----

[source, c++]
.new
----
// create a TPC/IP connection with the remote BAOS device

// with ScopedBaosConnection
ScopedBaosConnection connection("Baos-Sample");
BaosConnector::Ptr connector = connection.getConnector();

// or with BaosConnection
BaosConnection connection;
connection.connectIp("192.168.1.63", 0x20);
BaosConnector::Ptr connector = connection.getConnector();
----


Now you could also used the Connector direct.

[source, c++]
.new
----
// create a TPC/IP connection with the remote BAOS device (for protocol version 2.0)
StreamConnector20::Ptr connector = std::make_shared<StreamConnector20>();
connector->open("192.168.1.63", 12004);

// create a TPC/IP connection with the remote BAOS device (for protocol version 1.2)
StreamConnector12::Ptr connector = std::make_shared<StreamConnector12>("192.168.1.63", 12004);
connector->open();

// created a FT 1.2 connection with the BAOS device (only protocol version 2.0 supported)
FT12BaosConnector::Ptr connector = std::make_shared<FT12BaosConnector>();
connector->open("COM8");
        
----


=== Heartbeat

The remote device will close the connection if not activity is
noticed within a 2 minute period. 

In version <= 14.1.1p1 did the StreamConnector not send a heartbeat.
If you only periodically need to contact the remote device however 
need to connection to stay open you could used the BaosHearbeat class. 
BaosHeartbeat automatically keeps the TCP/IP connection alive.

Now the StreamConnector implemented internally the heartbeat.
So the BaosHeartbeat class is no more needed. Its exists only for backward compatibility.

[source, c++]
.old
----
ScopedStreamConnection connection("Baos-Sample");
BaosConnector::Ptr connector = connection.getConnector();
ScopedBaosHeartbeat baosHeartbeat(connector);
----

[source, c++]
.new
----
ScopedBaosConnection connection("Baos-Sample");
BaosConnector::Ptr connector = connection.getConnector();
----


=== DatapointValueIndicationQueue

The class DatapointValueIndicationQueue was already in an early version marked as deprecated.
Now we removed it. You could use the BaosEvent instead.

== .net Bindings

=== .net Assembly Name

Renamed from *kdriveRPC_baos_dotnet* to *kdriveBAOS_dotnet*

=== Namespace

The namespace was renamed from kdrive.rpc.baos.bindings to kdrive.baos.bindings

[source, c#]
.old (C#)
----
using kdrive.rpc.baos.bindings;
----

[source, c#]
.new (C#)
----
using kdrive.baos.bindings;
----


=== StreamConnection

The class StreamConnection is deprecated. Use BaosConnection instead. For more information see
also in the {cpp} section <<StreamConnection and ScopedStreamConnection>>.

[source, c#]
.old
----
StreamConnection connection = new StreamConnection()
connection.connectByName("Baos-Sample");
----

[source, c#]
.new
----
BaosConnection connection = new BaosConnection()
connection.connectIpByName("Baos-Sample");
----

=== Heartbeat

The class Heartbeat is deprecated.
Now the StreamConnector implemented internally the heartbeat.
So the BaosHeartbeat class is no more needed. Its exists only for backward compatibility.

[source, c#]
.old
----
// create the connection
StreamConnection connection = new StreamConnection();
connection.connect("192.168.1.23");
Connector connector = new Connector(connection);

// start the keep-alive thread
BaosHeartbeat heartbeat = new BaosHeartbeat(connector);
heartbeat.start();

// read a datapoint 
BaosDatapoint baosDatapoint = new BaosDatapoint(connector, 1);
bool value = baosDatapoint.getBoolean();       
----

[source, c#]
.new
----
// create the connection
BaosConnection connection = new BaosConnection();
connection.connect("192.168.1.23");
Connector connector = new Connector(connection);

// read a datapoint 
BaosDatapoint baosDatapoint = new BaosDatapoint(connector, 1);
bool value = baosDatapoint.getBoolean();       
----

== Foresight

[WARNING]
====
In the next versions we plan we removed the deprecated classes and functions.

Additionally we we will mark the protocol version 1.2 as deprecated.
But when a lot of people used it we will still support it.
====